<a href="https://colab.research.google.com/github/srija2771/pytorch3/blob/main/srija/00_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.1.0+cu121


In [3]:
## Introduction to Tensor
###creating sensors

In [4]:
#scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
#get tensor back as python int
scalar.item()

7

In [7]:
#vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#matrix
MATRIX=torch.tensor([[7,8],
                    [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
MATRIX.ndim

2

In [12]:
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
#tensor
TENSOR=torch.tensor([[[1,2,3],
                      [3,6,9],
                      [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

In [18]:
#create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.3882, 0.9646, 0.4257, 0.9404],
        [0.6061, 0.6994, 0.4947, 0.6787],
        [0.4081, 0.4237, 0.0700, 0.3655]])

In [19]:
#create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(224,224,3))
random_image_size_tensor.shape,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [20]:
#create a tensor of all zeros
zeros=torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [21]:
#create atensor of all ones
ones=torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [22]:
ones.dtype

torch.float32

In [23]:
random_tensor.dtype

torch.float32

In [24]:
#use torch.range()
a=torch.arange(start=1,end=11,step=1)
a

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
#creating a tensors like
ten_zeros=torch.zeros_like(input=a)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

Tensor datatypes

In [26]:
float_32_tensor=torch.tensor([3.0,6.0,9.0],
                             dtype=None,
                             device=None,
                             requires_grad=False)
float_32_tensor

tensor([3., 6., 9.])

In [27]:
float_32_tensor.dtype

torch.float32

In [28]:
float_16_tensor=float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [29]:
float_16_tensor*float_32_tensor

tensor([ 9., 36., 81.])

In [30]:
int_32_tensor=torch.tensor([3,6,9],dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [31]:
float_32_tensor*int_32_tensor

tensor([ 9., 36., 81.])

**getting information from tensors**

In [32]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.8063, 0.1728, 0.7375, 0.7473],
        [0.7835, 0.7439, 0.2726, 0.1238],
        [0.8889, 0.9409, 0.2591, 0.2290]])

In [33]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [34]:
some_tensor.size()

torch.Size([3, 4])

In [35]:
print(some_tensor)
print(f"Datatype of tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.shape}")
print(f"Device tensor is on:{some_tensor.device}")

tensor([[0.8063, 0.1728, 0.7375, 0.7473],
        [0.7835, 0.7439, 0.2726, 0.1238],
        [0.8889, 0.9409, 0.2591, 0.2290]])
Datatype of tensor:torch.float32
Shape of tensor:torch.Size([3, 4])
Device tensor is on:cpu


manipulating tensors (tensor operation)

In [36]:
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [37]:
tensor*10

tensor([10, 20, 30])

In [38]:
tensor

tensor([1, 2, 3])

In [39]:
tensor-10


tensor([-9, -8, -7])

In [40]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [41]:
torch.add(tensor,10)

tensor([11, 12, 13])

Matrix multiplication

In [42]:
torch.matmul(torch.rand(10,3),torch.rand(3,10))

tensor([[0.9151, 0.8115, 1.4372, 0.9884, 0.4183, 0.6832, 1.1972, 0.9919, 1.1347,
         0.5406],
        [0.9493, 0.7998, 1.4434, 0.7502, 0.5783, 0.8246, 1.1868, 1.1137, 1.2941,
         0.5287],
        [1.2583, 1.1307, 1.9957, 1.1829, 0.8297, 1.0064, 1.5514, 1.3951, 1.6475,
         0.7668],
        [0.8198, 0.6555, 1.2054, 0.5580, 0.4638, 0.7536, 1.0372, 1.0011, 1.1495,
         0.4236],
        [0.7322, 0.5339, 1.0163, 0.3752, 0.3519, 0.7306, 0.9483, 0.9503, 1.0696,
         0.3295],
        [0.5202, 0.4427, 0.7966, 0.3715, 0.3782, 0.4668, 0.6276, 0.6168, 0.7292,
         0.2961],
        [1.1446, 1.0482, 1.8390, 1.0622, 0.8462, 0.9176, 1.3776, 1.2614, 1.5109,
         0.7188],
        [0.9650, 0.7879, 1.4364, 0.8490, 0.3943, 0.8084, 1.2781, 1.1266, 1.2676,
         0.5072],
        [0.7163, 0.4585, 0.9184, 0.3195, 0.1502, 0.7443, 0.9984, 0.9753, 1.0498,
         0.2573],
        [1.0396, 0.7679, 1.4516, 0.8258, 0.2105, 0.9197, 1.4546, 1.2780, 1.3834,
         0.4652]])

In [43]:
torch.matmul(torch.rand(10,10),torch.rand(10,10)).shape

torch.Size([10, 10])

In [44]:
print(tensor,'*',tensor)
print(f"equals:{tensor*tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
equals:tensor([1, 4, 9])


In [45]:
torch.matmul(tensor,tensor)

tensor(14)

In [46]:
tensor

tensor([1, 2, 3])

In [47]:
1*1+2*2+3*3

14

In [48]:
tensor@tensor

tensor(14)

In [49]:
%%time
value=0
for i in range(len(tensor)):
  value+=tensor[i]*tensor[i]
print(value)

tensor(14)
CPU times: user 2.05 ms, sys: 0 ns, total: 2.05 ms
Wall time: 3.75 ms


In [50]:
%%time
torch.matmul(tensor,tensor)

CPU times: user 32 µs, sys: 0 ns, total: 32 µs
Wall time: 35.3 µs


tensor(14)

one of the most common errors in deep learning :shape error

In [51]:
tensor_A=torch.tensor([[1,2],
                      [3,4],
                      [5,6]])
tensor_B=torch.tensor([[7,10],
                       [8,11],
                       [9,12]])
#torch.mm(tensor_A,tensor_B)
torch.matmul(tensor_A,tensor_B)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [53]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [54]:
tensor_A.shape,tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [55]:
tensor_B,tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [56]:
tensor_B.T,tensor_B.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([3, 2]))

In [57]:
print(f"original shape:tensor_A={tensor_A.shape},tensor_B={tensor_B.shape}")
print(f"New  shapes:tensor_A={tensor_A.shape} (same shape as above),tensor_B.T={tensor_B.T.shape}")
print(f"Multiplying:{tensor_A.shape}@{tensor_B.T.shape}<-inner dimensions must match")
print("output:\n")
output=torch.matmul(tensor_A,tensor_B.T)
print(output)
print(f"\noutput shape:{output.shape}")

original shape:tensor_A=torch.Size([3, 2]),tensor_B=torch.Size([3, 2])
New  shapes:tensor_A=torch.Size([3, 2]) (same shape as above),tensor_B.T=torch.Size([2, 3])
Multiplying:torch.Size([3, 2])@torch.Size([2, 3])<-inner dimensions must match
output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

output shape:torch.Size([3, 3])


**Finding min,max,mean,sum,etc(tensor aggregatin)**

In [58]:
x=torch.arange(0,100,10)
x,x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [59]:
torch.min(x),x.min()

(tensor(0), tensor(0))

In [60]:
torch.max(x),x.max()

(tensor(90), tensor(90))

In [61]:
torch.mean(x.type(torch.float32)),x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [62]:
torch.sum(x),x.sum()

(tensor(450), tensor(450))

**finding th postional min and max**

In [63]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [64]:
x.argmin()

tensor(0)

In [65]:
x[0]

tensor(0)

In [66]:
x.argmax()

tensor(9)

In [67]:
x[9]

tensor(90)

**Reshaping,stacking,squeezing and unsqueezing**

In [68]:
import torch
x=torch.arange(1.,10.)
a,a.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [69]:
x_reshaped=x.reshape(1,9)
x_reshaped,x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [70]:
z=x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [72]:
x_stacked=torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [73]:
print(f"previous tensor:{x_reshaped}")
print(f"previous shape:{x_reshaped.shape}")
x_squeezed=x_reshaped.squeeze()
print(f"\nNew tensor:{x_squeezed}")
print(f"New shape:{x_squeezed.shape}")

previous tensor:tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
previous shape:torch.Size([1, 9])

New tensor:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape:torch.Size([9])


In [74]:
print(f"previous target:{x_squeezed}")
print(f"previous shape:{x_squeezed.shape}")
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
print(f"\n New tensor:{x_unsqueezed}")
print(f"New shape:{x_unsqueezed.shape}")

previous target:tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
previous shape:torch.Size([9])

 New tensor:tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
New shape:torch.Size([9, 1])


In [75]:
x_original=torch.rand(size=(224,224,3))
x_permuted=x_original.permute(2,0,1)
print(f"previous shape:{x_original.shape}")
print(f"New shape:{x_permuted.shape}")

previous shape:torch.Size([224, 224, 3])
New shape:torch.Size([3, 224, 224])


In [76]:
x_original

tensor([[[0.1573, 0.3267, 0.6947],
         [0.3772, 0.1150, 0.5579],
         [0.0983, 0.9483, 0.0376],
         ...,
         [0.4860, 0.9970, 0.1280],
         [0.5788, 0.8584, 0.2043],
         [0.9566, 0.1390, 0.3744]],

        [[0.7775, 0.1673, 0.8431],
         [0.0118, 0.9117, 0.8849],
         [0.9277, 0.9532, 0.6499],
         ...,
         [0.6841, 0.0332, 0.4882],
         [0.5881, 0.5065, 0.5512],
         [0.4239, 0.4211, 0.8941]],

        [[0.3534, 0.1436, 0.7230],
         [0.0406, 0.1431, 0.3356],
         [0.6153, 0.9141, 0.3307],
         ...,
         [0.4813, 0.2315, 0.0374],
         [0.3241, 0.7025, 0.2787],
         [0.1997, 0.5002, 0.2421]],

        ...,

        [[0.6873, 0.2757, 0.9583],
         [0.2832, 0.3874, 0.8878],
         [0.3187, 0.9845, 0.0730],
         ...,
         [0.9116, 0.5072, 0.3351],
         [0.8683, 0.8613, 0.4424],
         [0.4333, 0.8730, 0.3589]],

        [[0.0646, 0.7474, 0.2869],
         [0.6932, 0.3934, 0.8375],
         [0.

In [77]:
x_original[0,0,0]=728218
x_original[0,0,0],x_permuted[0,0,0]

(tensor(728218.), tensor(728218.))

**Indexing(selecting data from tensors)**

indexing with pytorch is similar to indexing with numpy

In [78]:
import torch
x=torch.arange(1,10).reshape(1,3,3)
x,x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [79]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [80]:
x[0][0]

tensor([1, 2, 3])

In [81]:
x[0][1][1]

tensor(5)

In [82]:
x[:,0]

tensor([[1, 2, 3]])

In [83]:
x[:,:,1]

tensor([[2, 5, 8]])

In [84]:
x[:,1,1]

tensor([5])

In [85]:
x[0,0,1]

tensor(2)

In [86]:
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [87]:
print(x[0][2][2])
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


**pytorch tensors and Numpy**


In [88]:
import torch
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array).type(torch.float32)
array,tensor


(array([1., 2., 3., 4., 5., 6., 7.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [89]:
array.dtype

dtype('float64')

In [90]:
torch.arange(1.0,8.0).dtype

torch.float32

In [91]:
array=array+1
array,tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [92]:
tensor=torch.ones(7)
numpy_tensor=tensor.numpy()
tensor,numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [93]:
tensor=tensor+1
tensor,numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

**Reproducbility(trying to take random out of random)**

In [94]:
torch.rand(3,3)

tensor([[0.1793, 0.1650, 0.0722],
        [0.5556, 0.4447, 0.9156],
        [0.8166, 0.3822, 0.5977]])

In [95]:
import torch
random_tensor_A=torch.rand(3,4)
random_tensor_B=torch.rand(3,4)
print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A==random_tensor_B)

tensor([[0.1487, 0.9000, 0.3921, 0.5592],
        [0.7460, 0.5633, 0.6872, 0.1185],
        [0.6435, 0.8090, 0.1809, 0.0175]])
tensor([[0.6537, 0.7902, 0.5300, 0.4931],
        [0.5900, 0.1705, 0.1529, 0.8466],
        [0.2872, 0.6436, 0.0499, 0.9789]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [96]:
import torch
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)
random_tensor_C=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_D=torch.rand(3,4)
print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C==random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


**Extra resources for reproducibility**

In [97]:
!nvidia-smi

Sun Feb 11 16:02:40 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8               9W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--